artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/gititsid/Datasets/raw/main/CreditRiskModelingData.zip
  data_file: artifacts/data_ingestion/CreditRiskModelingData.zip
  unzip_dir: artifacts/data_ingestion
  internal_raw_file: artifacts/data_ingestion/case_study1.xlsx
  external_raw_file: artifacts/data_ingestion/case_study2.xlsx

data_validation:
  root_dir: artifacts/data_validation
  internal_raw_file: artifacts/data_ingestion/case_study1.xlsx
  external_raw_file: artifacts/data_ingestion/case_study2.xlsx
  internal_file_val_status: artifacts/data_validation/internal_file_val_status.txt
  external_file_val_status: artifacts/data_validation/external_file_val_status.txt

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  internal_raw_file: artifacts/data_ingestion/case_study1.xlsx
  external_raw_file: artifacts/data_ingestion/case_study2.xlsx
  cleaned_raw_dataset: artifacts/data_preprocessing/CreditRiskModelingData.csv
  preprocessed_dataset: artifacts/data_preprocessing/processed_data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  preprocessed_dataset: artifacts/data_preprocessing/processed_data.csv
  data_transformer: artifacts/data_transformation/data_transformer.pkl


